chore: start collectors architecture
DXHeroes/dx-scanner pull request #377
Opened 2020-08-10 07:33 UTC by prokopsimek

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-08-20 12:20 UTC, adelkahomolova requested changes

2020-08-20 12:20 UTC, adelkahomolova commented on src/services/bitbucket/BitbucketService.ts
> +        //filter diplicate commiter names
```suggestion
        //filter duplicate committer names
```

2020-08-20 12:20 UTC, adelkahomolova commented on src/services/bitbucket/BitbucketService.ts
> +  private async paginate(method: (params: Params.RepositoriesListCommits) => AsyncResponse<any>, params: Params.RepositoriesListCommits) {
rename or make it generic

2020-08-20 12:20 UTC, adelkahomolova commented on src/services/gitlab/GitLabService.ts
> +        //filter diplicate commiter names
```suggestion
        //filter duplicate committer names
```

2020-08-25 10:12 UTC, adelkahomolova approved these changes

2020-08-25 10:21 UTC, Jakub-Vacek approved these changes

2020-08-25 10:22 UTC, merged

2020-08-25 10:38 UTC, prokopsimek commented
:tada: This PR is included in version 3.35.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dx-scanner/v/3.35.0)
- [GitHub release](https://github.com/DXHeroes/dx-scanner/releases/tag/v3.35.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: