Added a CppComponentDetector
DXHeroes/dx-scanner pull request #434
Opened 2020-10-01 15:06 UTC by iamRishabh07

## Description

Fixes #64 
Added a C++ Component detector which will measure the quality of apps written in C++.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [x ] I have added new practice to practice list in README.md.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-01 15:09 UTC, adelkahomolova commented
Thank you for your PR! @iamRishabh07 Can you add tests for your code? Thanks :)

2020-10-01 15:19 UTC, adelkahomolova commented
Also, you need to add code to [languageContextBinding.ts](https://github.com/DXHeroes/dx-scanner/blob/master/src/contexts/language/languageContextBinding.ts) and [index.ts](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/index.ts). Your code wouldn't be working without these additions. @iamRishabh07

2020-10-04 19:05 UTC, iamRishabh07 commented
@adelkahomolova Can you provide me any reference on what kind of test to add.

2020-10-05 07:19 UTC, adelkahomolova commented
Look at [JavaScriptComponentDetector.spec.ts](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/JavaScript/JavaScriptComponentDetector.spec.ts), [JavaComponentDetector.spec.ts](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/Java/JavaComponentDetector.spec.ts) or any other tests for component detectors in [detectors folder](https://github.com/DXHeroes/dx-scanner/tree/master/src/detectors) 😉

2020-10-07 11:20 UTC, adelkahomolova commented
@iamRishabh07 Hi, how are you going with the tests and the small additions I mentioned above? :)

2020-10-07 14:53 UTC, iamRishabh07 commented
@adelkahomolova I have made the required changes. Do I also need to add the PackageInspector?

2020-10-08 08:13 UTC, adelkahomolova commented
That would be awesome, if you'll add also Package Inspector. Because after that, the dxs-scanner will support C++. Thank you for the question. You can get the inspiration from [JavaScriptPackageInspector](https://github.com/DXHeroes/dx-scanner/blob/master/src/inspectors/package/JavaScriptPackageInspector.ts), or [JavaScriptPackageInspector](https://github.com/DXHeroes/dx-scanner/blob/master/src/inspectors/package/JavaScriptPackageInspector.ts) or any other package inspector from [package folder](https://github.com/DXHeroes/dx-scanner/tree/master/src/inspectors/package). Don't forget about tests. Thank you, @iamRishabh07  :)

2020-10-09 11:00 UTC, iamRishabh07 commented
@adelkahomolova what is the use of Gradle and Maven in JavaPackageInspector?

2020-10-11 08:14 UTC, adelkahomolova commented
Both are similar to `package.json` for javascript. It's a build and dependency resolution tool for Java. @iamRishabh07

2020-10-15 10:42 UTC, adelkahomolova commented
Hi @iamRishabh07 is there any progress? :)

2020-10-15 21:43 UTC, iamRishabh07 commented
@adelkahomolova I have made the changes as required. And for the package Inspector, I am still figuring it out.

2020-10-16 09:08 UTC, adelkahomolova requested changes

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/LanguageContext.ts
> +}
add a new line at end of a file
```suggestion
}

```

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> +const resolveBindingPackageInspector = (packageInspector: { new(...args: any[]): PackageInspectorBase }, container: Container) => {
```suggestion
const resolveBindingPackageInspector = (packageInspector: { new (...args: any[]): PackageInspectorBase }, container: Container) => {
```

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> +  componentDetector: { new(...args: any[]): IProjectComponentDetector };
```suggestion
  componentDetector: { new (...args: any[]): IProjectComponentDetector };
```

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> -
Why did you remove the line?

2020-10-16 09:08 UTC, adelkahomolova commented on src/contexts/language/languageContextBinding.ts
> +};
add new line
```suggestion
};

```

2020-10-16 09:08 UTC, adelkahomolova commented on src/detectors/Cpp/CPPComponentDetector.spec.ts
> +    const MockedCPPPackageInspector = <jest.Mock<CPPPackageInspector>>(<unknown>CPPPackageInpector);
```suggestion
    const MockedCPPPackageInspector = <jest.Mock<CPPPackageInspector>>(<unknown>CPPPackageInspector);
```

2020-10-16 09:08 UTC, adelkahomolova commented on src/detectors/index.ts
> +export * from './IScanningStrategy';
add new line
```suggestion
export * from './IScanningStrategy';

```

2020-10-16 09:08 UTC, adelkahomolova commented on src/model.ts
> +export type VCSService = GitHubService | BitbucketService | GitLabService;
add new line
```suggestion
export type VCSService = GitHubService | BitbucketService | GitLabService;

```

2020-10-26 09:47 UTC, adelkahomolova commented
Hi, @iamRishabh07 , is there any progress? :)

2020-11-05 14:19 UTC, prokopsimek commented
/close Invalid

2020-11-05 14:19 UTC, closed without merging