Initial Commit
DXHeroes/dx-scanner pull request #451
Opened 2020-10-11 11:19 UTC by gagandeepp

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-11 11:20 UTC, gagandeepp commented
Which Linter you want to use ??

2020-10-14 08:13 UTC, adelkahomolova commented
Hi, firstly I'm really sorry for the long delay. I had a crazy week. @gagandeepp 
I don't know which linter you should check. I'm not a C# developer and choosing the right one is a part of the task. 
I'll also ask you for a renaming pull request since it's not an initial commit and also for fill in the PR template. Thanks :)

2020-10-16 18:45 UTC, adelkahomolova requested changes

2020-10-16 18:45 UTC, adelkahomolova commented on src/practices/C#/CsharpLinterUsedPractice.ts
> +      if (ctx.packageInspector.hasOneOfPackages(['golang.org/x/lint', 'github.com/golangci/golangci-lint'])) {
Choose the most used C# linter.

2020-10-19 09:07 UTC, adelkahomolova commented
Hi, @gagandeepp , how are you? Is there any progress with this PR? :)

2020-10-19 14:51 UTC, gagandeepp commented
> Hi, @gagandeepp , how are you? Is there any progress with this PR? :)

In C# we used IDE built in code analysis which is available as DLL ,so I am not sure whether this change can be implemented.

2020-10-19 15:30 UTC, adelkahomolova commented
@gagandeepp Look at this article. Some of them should be able to use for this practice. https://medium.com/@michaelparkerdev/linting-c-in-2019-stylecop-sonar-resharper-and-roslyn-73e88af57ebd

2020-10-26 09:50 UTC, adelkahomolova commented
Hi, @gagandeepp , is there any progress? :)

2020-10-27 04:57 UTC, gagandeepp commented
> Hi, @gagandeepp , is there any progress? :)

Sorry I am unable to a make progress on this

2020-10-27 14:48 UTC, closed without merging