fix: find user by email
DXHeroes/dx-scanner pull request #456
Opened 2020-10-13 14:46 UTC by Jakub-Vacek

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-14 05:00 UTC, prokopsimek requested changes

2020-10-14 05:00 UTC, prokopsimek commented on src/services/gitlab/GitLabService.ts
> +              id: commit.short_id,
this is invalid quick fix with this id

2020-10-15 06:54 UTC, prokopsimek approved these changes

2020-10-15 08:39 UTC, adelkahomolova approved these changes

2020-10-15 08:39 UTC, merged

2020-10-15 08:51 UTC, prokopsimek commented
:tada: This PR is included in version 3.41.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dx-scanner/v/3.41.2)
- [GitHub release](https://github.com/DXHeroes/dx-scanner/releases/tag/v3.41.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: