Add branch list for GitLab
DXHeroes/dx-scanner pull request #470
Opened 2020-10-22 13:51 UTC by vlasy

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-22 19:49 UTC, adelkahomolova approved these changes

2020-10-22 19:50 UTC, adelkahomolova requested changes
What about tests?

2020-10-23 04:52 UTC, prokopsimek approved these changes

2020-11-05 11:05 UTC, adelkahomolova approved these changes

2020-11-05 11:58 UTC, merged

2020-11-05 15:42 UTC, prokopsimek commented
:tada: This PR is included in version 3.46.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dx-scanner/v/3.46.0)
- [GitHub release](https://github.com/DXHeroes/dx-scanner/releases/tag/v3.46.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: