Fallback to local path when repo scan fails
DXHeroes/dx-scanner pull request #487
Opened 2020-11-27 10:47 UTC by vlasy

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Resolves #483

2020-11-28 08:01 UTC, prokopsimek requested changes
@vlasy The fix seems to be ok but tests are missing. Please add a test for new changes. Thanks!

2020-12-03 13:12 UTC, vlasy commented
> @vlasy The fix seems to be ok but tests are missing. Please add a test for new changes. Thanks!

Added a test

2020-12-04 13:01 UTC, adelkahomolova approved these changes

2020-12-04 13:15 UTC, Jakub-Vacek approved these changes

2020-12-04 13:15 UTC, merged

2020-12-07 07:18 UTC, prokopsimek commented
:tada: This PR is included in version 3.46.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dx-scanner/v/3.46.3)
- [GitHub release](https://github.com/DXHeroes/dx-scanner/releases/tag/v3.46.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: