fix: make lockfile practice only for js and ts
DXHeroes/dx-scanner pull request #518
Opened 2021-01-27 14:33 UTC by Jakub-Vacek

## Description

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-01-27 14:43 UTC, adelkahomolova requested changes
https://github.com/DXHeroes/dx-scanner/pull/518/files#diff-5e2541ee93e2fadb03917727f0cefa1699027b6e647e1201f88d2455a6d799b4L9 change the id

2021-02-01 07:16 UTC, prokopsimek approved these changes

2021-02-01 08:26 UTC, adelkahomolova approved these changes

2021-02-01 08:27 UTC, merged

2021-02-01 10:44 UTC, prokopsimek commented
:tada: This PR is included in version 3.51.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dx-scanner/v/3.51.1)
- [GitHub release](https://github.com/DXHeroes/dx-scanner/releases/tag/v3.51.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: